[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=1
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\Yehpeng\AppData\Local\Temp\imgpdf2epub-build\out\ImgPdf2Epub-Setup.exe
FriendlyName=ImgPdf2Epub Setup
AppLaunched=install.cmd
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles
[Strings]
FILE0="payload.zip"
FILE1="install.cmd"
FILE2="install.ps1"
[SourceFiles]
SourceFiles0=C:\Users\Yehpeng\AppData\Local\Temp\imgpdf2epub-build\
[SourceFiles0]
%FILE0%=
%FILE1%=
%FILE2%=
